{
  imports = [
    ./accel-ppp.nix
    ./databases/mysql.nix
    ./databases/postgres.nix
    ./gitea.nix
    ./glanceapp.nix
    ./gotify.nix
    ./grafana.nix
    ./nameserver.nix
    ./nginx.nix
    ./recursivedns.nix
    ./rustdesk-server.nix
    ./traefik.nix
    ./uptime-kuma.nix
    ./vaultwarden.nix
    ./wordpress.nix
    ./zammad.nix
  ];
}
